# Generated by Django 4.1 on 2023-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babyurlbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlmapping",
            name="target_url",
            field=models.URLField(max_length=1000),
        ),
    ]
