# Generated by Django 4.1.3 on 2023-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcfixturebot", "0002_remove_schedule_user_id_schedule_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="team_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
