# Generated by Django 4.1.3 on 2023-01-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kcfixturebot", "0003_schedule_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="fixture_schedule",
            new_name="reminder_day",
        ),
    ]
