# Generated by Django 4.1.3 on 2023-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcfixturebot", "0004_rename_fixture_schedule_schedule_reminder_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="game_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="game_day",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="game_time",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
